export default {
    GROUP_SCREEN: 'GROUP_SCREEN',
    ADD_PRODUCT_LIST: 'ADD_PRODUCT_LIST',

    MAIN_SCREEN: 'MAIN_SCREEN',
    PRODUCT_MAGAZINE: 'PRODUCT_MAGAZINE',
    STATISTICS_SCREEN: 'STATISTICS_SCREEN',
    SETTINGS_SCREEN: 'SETTINGS_SCREEN',


    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',

    EB_LOGIN_FORM: 'EB_LOGIN_FORM',
    EB_REGISTRATION_FORM: 'EB_REGISTRATION_FORM'
};